HRSystem/Models/PermissionRequest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PermissionRequest
    {
        public long Id { get; set; }
        public string EmployeeNo { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime RequestDate { get; set; }
        public int TimeFromHours { get; set; }
        public Nullable<int> TimeFromMinutes { get; set; }
        public int TimeToHours { get; set; }
        public Nullable<int> TimeToMinutes { get; set; }
        [Required(ErrorMessageResourceType = typeof(NubiHR), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(NubiHR), Name = "PermissionDate")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]

        public System.DateTime PermissionDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> LeaderApprovement { get; set; }
        public Nullable<bool> ManagerApprovement { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public int PermissionTypeNo { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> LeaderHasSeen { get; set; }
        public Nullable<bool> ManagerHasSeen { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual PermissionType PermissionType { get; set; }
    }
}

HRSystem/Controllers/PermissionRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRSystem.Models;
using Microsoft.AspNet.Identity;
using System.Globalization;

namespace HRSystem.Controllers
{
    [Authorize]
    public class PermissionRequestController : BaseController
    {
        NubiDBEntities db = new NubiDBEntities();

        // GET: PermissionRequest
        public ActionResult Index()
        {
            Manager.RequestManager mng = new Manager.RequestManager();
            ViewBag.per = mng.GetPermission(id: User.Identity.GetUserId());

            var current = System.Globalization.CultureInfo.CurrentCulture;
            current.DateTimeFormat.Calendar = new GregorianCalendar();
            current.DateTimeFormat.ShortDatePattern = "MM/dd/yyyy";

            return View(db.PermissionRequests.ToList());
        }
        public ActionResult LeaderRequests()
        {
            var permission = db.PermissionRequests.Where(x => x.LeaderApprovement == null).ToList();
            foreach (PermissionRequest per in permission)

            {

                PermissionRequest Existing_per = db.PermissionRequests.Find(per.Id);

                Existing_per.LeaderHasSeen = true;

            }
            db.SaveChanges();
            var current = System.Globalization.CultureInfo.CurrentCulture;
            current.DateTimeFormat.Calendar = new GregorianCalendar();
            current.DateTimeFormat.ShortDatePattern = "MM/dd/yyyy";

            return View(db.PermissionRequests.OrderBy(e => e.RequestDate));
        }
        public ActionResult LeaderApprove(int id)
        {
            PermissionRequest per = db.PermissionRequests.Find(id);
            if (ModelState.IsValid)
            {
                per.LeaderApprovement = true;
                db.Entry(per).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("LeaderRequests");
            }
            return View(db.PermissionRequests.OrderBy(e => e.RequestDate));
        }
        public ActionResult Reject(int id)
        {
            PermissionRequest per = db.PermissionRequests.Find(id);
            if (ModelState.IsValid)
            {
                per.IsRejected = true;
                db.Entry(per).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("LeaderRequests");
            }
            return View(db.PermissionRequests.ToList());
        }
        public ActionResult ManagerRequests()
        {
            var permission = db.PermissionRequests.Where(x => x.LeaderApprovement == true).ToList();
            foreach (PermissionRequest per in permission)

            {

                PermissionRequest Existing_per = db.PermissionRequests.Find(per.Id);

                Existing_per.ManagerHasSeen = true;

            }
            db.SaveChanges();
            var current = System.Globalization.CultureInfo.CurrentCulture;
            current.DateTimeFormat.Calendar = new GregorianCalendar();
            current.DateTimeFormat.ShortDatePattern = "MM/dd/yyyy";

            return View(db.PermissionRequests.OrderBy(e => e.RequestDate));
        }

        public ActionResult ManagerApprove(int id)
        {
            PermissionRequest per = db.PermissionRequests.Find(id);
            if (ModelState.IsValid)
            {
                per.ManagerApprovement = true;
                db.Entry(per).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManagerRequests");
            }
            return View(db.PermissionRequests.ToList());
        }

        public ActionResult Create()
        {
            Manager.RequestManager mng = new Manager.RequestManager();
            ViewBag.per = mng.GetPermission(id: User.Identity.GetUserId());
            ViewBag.PermissionTypeNo = new SelectList(db.PermissionTypes.ToList(), "Id", "Type");
            return View();
            
        }
        
        // POST: /PermissionRequest/Create
        [HttpPost]
        public ActionResult Create(PermissionRequest per, string PerDateAr)
        {
            ModelState.Remove("PermissionDate");
            Manager.RequestManager mng = new Manager.RequestManager();
            ViewBag.per = mng.GetPermission(id: User.Identity.GetUserId());
            var CurrentUser = User.Identity.GetUserId();
            per.EmployeeNo = db.AspNetUsers.Where(a => a.Id == CurrentUser).FirstOrDefault().EmpNo;
            var IsArabic = Request.Cookies["culture"].Value == "ar" ? true : false;
            if (IsArabic)
            {


                CultureInfo MyCultureInfo = new CultureInfo("en-GB");
                DateTime.Parse(PerDateAr, MyCultureInfo);
                per.PermissionDate = DateTime.Parse(PerDateAr, MyCultureInfo);

                //DateTime.Now.ToString("dd dddd , MMMM, yyyy", new CultureInfo("ar-AE"));
                /*vac.StartDate =new DateTime(2018,12,12);*//* DateTime.Parse(StartDateAr, MyCultureInfo);*/
                //vac.StartDate = Convert.ToDateTime(StartDateAr,);
                //vac.StartDate.ToString("dd dddd , MMMM, yyyy", new CultureInfo("en-US"));

                //CultureInfo MyCultureInfo = new CultureInfo("en-US");
                //MyCultureInfo.DateTimeFormat.Calendar = new HijriCalendar();
                //vac.StartDate = DateTime.Parse(StartDateAr, MyCultureInfo);

                //CultureInfo arSA = new CultureInfo("ar-SA");
                //arSA.DateTimeFormat.Calendar = new HijriCalendar();
                //vac.StartDate = DateTime.ParseExact(StartDateAr, "dd/MM/yyyy", arSA);

            }
            if (per.PermissionDate < DateTime.Today)
            {
                ModelState.AddModelError("PermissionDate", "Permission date not valid");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    //const int maxTimesAsSeconds = 14400;
                    //int timeto = Convert.ToInt32(per.TimeTo);
                    //int timefrom = Convert.ToInt32(per.TimeFrom);
                    //var difference = Math.Abs(timeto - timefrom);

                    //var hf = 17;
                    //var mf = 20;
                    //per.TimeFrom = new TimeSpan(hours: , minutes: , 0);

                    //var ht = 20;
                    //var mt = 40;
                    //per.TimeTo = new TimeSpan(hours:, minutes:, 0);

                    //var differnceAs = per.TimeTo.Subtract(per.TimeFrom);
                    //var differnceAs_time = TimeSpan.FromMilliseconds(differnceAs_s);

                    //var TimeFromHours = per.TimeFromHours;
                    //var TimeFromMinutes = per.TimeFromMinutes;
                    //var TimeToHours = per.TimeToHours;
                    //var TimeToMinutes = per.TimeToMinutes;
                    ViewBag.PermissionTypeNo = new SelectList(db.PermissionTypes.ToList(), "Id", "Type");
                    TimeSpan timeFrom = new TimeSpan(0, per.TimeFromHours, per.TimeFromMinutes ?? 0, 0);
                    TimeSpan timeTo = new TimeSpan(0, per.TimeToHours, per.TimeToMinutes ?? 0, 0);

                    //var differnce = timeTo - timeFrom;

                    //if (differnce.TotalHours > 4 )
                    //{
                    //    TempData["checkHours"] = "You Can Not Take More Than 4 Hours!";
                    //    ViewBag.PermissionTypeNo = new SelectList(db.PermissionTypes.ToList(), "ID", "Type");
                    //}
                    //else
                    //{
                    per.RequestDate = DateTime.Now;
                    per.TimeToHours = timeFrom.Hours + 4;
                    if (per.TimeToHours > 16)
                    {
                        per.TimeToHours = 16;
                        per.TimeToMinutes = 0;
                    }
                    else
                    {
                        per.TimeToMinutes = timeFrom.Minutes;
                    }
                    
                    per.LeaderApprovement = true;
                    TempData["chec"] = Resources.NubiHR.YourRequestHasBeenSented;
                    db.PermissionRequests.Add(per);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                    //}
                }
            }
            ViewBag.PermissionTypeNo = new SelectList(db.PermissionTypes.ToList(), "Id", "Type");
            return View();
        }


        //GET: /PermissionRequest/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                HttpNotFound();
            }
            PermissionRequest per = db.PermissionRequests.Find(id);
            if (per == null)
            {
               return HttpNotFound();
            }
            ViewBag.PermissionTypeNo = new SelectList(db.PermissionTypes.ToList(), "Id", "Type");
            //ViewBag.PermissionTypeNo = new SelectList(db.PermissionTypes.ToList(), "ID","Type",per.PermissionTypeNo);
            return View(per);
        }

        // POST: /PermissionRequest/Edit
        [HttpPost]
        public ActionResult Edit(int id, PermissionRequest per, string PerDateAr)
        {
            per.Id = id;
            string CurrentUser = User.Identity.GetUserId();
            per.EmployeeNo = db.AspNetUsers.Where(e => e.Id == CurrentUser).FirstOrDefault().EmpNo;
            var IsArabic = Request.Cookies["culture"].Value == "ar" ? true : false;
            if (IsArabic)
            {
                CultureInfo MyCultureInfo = new CultureInfo("en-GB");
                DateTime.Parse(PerDateAr, MyCultureInfo);
                per.PermissionDate = DateTime.Parse(PerDateAr, MyCultureInfo);
            }
            if (ModelState.IsValid)
            {

HRSystem/Views/PermissionRequest/Create.cshtml
@model HRSystem.Models.PermissionRequest
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = Resources.NubiHR.CreatePermissionRequest;
    HRSystem.Manager.Helper helperx = new HRSystem.Manager.Helper();
    HRSystem.Manager.RequestManager mngr = new HRSystem.Manager.RequestManager();
}

<style>
    .tooltip {
        position: relative;
        display: inline-block;
        border-bottom: 1px dotted black;
    }

        .tooltip .tooltiptext {
            visibility: hidden;
            width: 120px;
            background-color: red;
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            /* Position the tooltip */
            position: absolute;
            z-index: 1;
            top: -3px;
            left: 103%;
        }

        .tooltip:hover .tooltiptext {
            visibility: visible;
        }
</style>
<h2>@Resources.NubiHR.CreatePermissionRequest</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form" }))
{
    <div class="form-group col-md-6">
        @*<div>
           Request Date
        </div>
        <div>
          @Html.EditorFor(model => model.RequestDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RequestDate, "", new { @class = "text-danger" })
        </div>
        <br />*@
        <div>
            @Resources.NubiHR.EmployeeName
        </div>
        <div>
            <label> @helperx.GetName(User.Identity.GetUserId()).Employee.FirstName</label>
        </div>
        <br />
        <div>
            @Resources.NubiHR.Position
        </div>
        <div>
            <label> @helperx.GetUserRole(User.Identity.GetUserId())</label>
        </div>
        <br />
        <div>
            @Resources.NubiHR.PermissionType
        </div>
        <div>
            @Html.DropDownList("PermissionTypeNo", null, "Select", new { @class = "form-control" })

        </div>
        <br />
        <div>
            @Resources.NubiHR.PermissionDate
        </div>

        <div class="input-group mb-4">
            @Html.EditorFor(model => model.PermissionDate, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            <div class="input-group-append">
                <span class="fa fa-calendar input-group-text start_date_calendar" aria-hidden="true"></span>
            </div>
            @Html.Hidden("PerDateAr")

        </div>
        @Html.ValidationMessageFor(model => model.PermissionDate, "", new { @class = "text-danger" })
        <br />
        <br />
        <div>
            @Resources.NubiHR.Period:
        </div>
        <div>
            @Resources.NubiHR.TimeFrom  <label style="color:red ; font-weight:bold">24 Hour system</label>
        </div>
        <br />
        <div class="row">
            <label>@Resources.NubiHR.Hour</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.TimeFromHours, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.TimeFromHours, "", new { @class = "text-danger" })
            </div>
            <label>@Resources.NubiHR.Minute</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.TimeFromMinutes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeFromMinutes, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div>
            @Resources.NubiHR.TimeTo
        </div>
        <br />
        <div class="row">
            <label>@Resources.NubiHR.Hour</label>
            <div class="col-md-4" id="TimeTo" style="color: #de340d">
                @*@Html.EditorFor(model => model.TimeToHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeToHours, "", new { @class = "text-danger" })*@
            </div>
            <label>@Resources.NubiHR.Minute</label>
            <div class="col-md-4" id="TimeToMinute" style="color: #de340d">

            </div>
        </div>
        <br />
        <div>
            @Resources.NubiHR.Notes
        </div>
        <div>
            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
        </div>
        <br />
        <div class="form-group">
            <div>
                @if (ViewBag.per)
                {
                    <input type="submit" value=@Resources.NubiHR.Send class="btn2" />
                }
                else
                {
                    <button class="btn2disabled tooltip text-center" disabled style="cursor:not-allowed; font-weight: 500; font-size: medium;">
                        @Resources.NubiHR.Send
                        <span class="tooltiptext">You cant take permission</span>
                        </button>
                    @*<button class="tooltip btn2disabled" disabled style="cursor:not-allowed" value=@Resources.NubiHR.Send>*@
                        @*<input type="submit" value=@Resources.NubiHR.Send class="btn2disabled tooltip" disabled style="cursor:not-allowed" />*@
                        @*<span class="tooltiptext">Tooltip text</span>*@
                    @*</button>*@
                    
                }
                
   
            </div>
            <br />
            <div>
                <a href="@Url.Action("Index")" class="btn-Back" style="color:white; text-decoration: none;">@Resources.NubiHR.Back</a>
            </div>
        </div>
    </div>
}

<script>
    $("#TimeFromHours").change(function () {
        var date = new Date($("#PermissionDate").val());
        var hours = parseInt($("#TimeFromHours").val());
        //$("#TimeToMinute") = $("#TimeFromMinutes").val();
        var minute = parseInt($("#TimeFromMinutes").val());

        $("#TimeToMinute").show();
        $("#TimeToMinute").text($("#TimeFromMinutes").val());

        var inchours = hours + 4;
        if (inchours >= 16)
        {
            $("#TimeTo").text("Rest of the day");
            $("#TimeToMinute").text("0");
        }
        else if (inchours <= 16 && minute === "")
        {
            $("#TimeTo").text(hours + 4);
            $("#TimeToMinute").hide();
        }
            

       else 
            $("#TimeTo").text(hours + 4);
        $("#TimeFromMinutes").change(function () {
            $("#TimeToMinute").show();
            $("#TimeToMinute").text($("#TimeFromMinutes").val());
            //$("#TimeToMinute").text(minute);
        })
         

        //else
        //    $("#TimeTo").text(hours + 4);
        //    $("#TimeToMinute").text(minute);


        //var timefrom = new Date(date.getFullYear, date.getMonth, date.getDay, $("#TimeFromHours").val(), $("#TimeFromMinutes").val());
        //var hours = date.getHours();
        //var incrHours = hours + 4;
        //var timeto = timefrom.setHours(timefrom.getHours() + 4);

        //$("#TimeTo").text(timefrom.setHours(timefrom.getHours() + 4));

        //var date1 = new Date();
        //date1.setHours(date1.getHours() + 5);

    })

    $("#PermissionDate").change(function () {
        $("#PerDateAr").val($("#PermissionDate").val());
    })
</script>

HRSystem/Views/PermissionRequest/Delete.cshtml
@model HRSystem.Models.PermissionRequest
@{
    ViewBag.Title = Resources.NubiHR.Delete;
}

<h2>@Resources.NubiHR.Delete</h2>
@using (Html.BeginForm(null, null, FormMethod.Post))
{
    <h3>@Resources.NubiHR.AreYouSureYouWantToDeleteThis</h3>

    <div>

        @Html.ActionLink(Resources.NubiHR.Back, "Index", new { @class = "btn btn-primary" }) |
        <input type="submit" value=@Resources.NubiHR.Delete class="btn btn-danger" />
    </div>
}

HRSystem/Views/PermissionRequest/LeaderRequests.cshtml
@model IEnumerable<HRSystem.Models.PermissionRequest>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "LeaderRequests";
    HRSystem.Manager.Helper helperx = new HRSystem.Manager.Helper();
    HRSystem.Manager.RequestManager mngr = new HRSystem.Manager.RequestManager();
    var IsArabic = Request.Cookies["culture"].Value == "ar" ? true : false;
}

<h2>@Resources.NubiHR.PermissionRequests</h2>



<table id="assets-data-table" class="table table-striped table-bordered table-responsive">
    <thead>
        <tr>
            <th>
                @Resources.NubiHR.EmployeeName
            </th>
            
            <th>
                @Resources.NubiHR.Position
            </th>
            
            <th>
                @Resources.NubiHR.RequestDate
            </th>
           
            <th>
                @Resources.NubiHR.PermissionDate
            </th>
            
            <th>
                @Resources.NubiHR.PermissionType
            </th>

            <th>
                @Resources.NubiHR.TimeFrom
            </th>

            <th>
                @Resources.NubiHR.TimeTo
            </th>
            
            <th>
                @Resources.NubiHR.Notes
            </th>

            <th>
                @Resources.NubiHR.Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Where(e => e.LeaderApprovement == null).ToList())
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.FirstName)
                </td>
                @if (IsArabic)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Position.PositionNameAr)
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Position.PositionNameEn)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.RequestDate)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.PermissionDate)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.PermissionType.Type)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.TimeFromHours) : @Html.DisplayFor(modelItem => item.TimeFromMinutes)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.TimeToHours) : @Html.DisplayFor(modelItem => item.TimeToMinutes)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>

                <td>
                    @Html.ActionLink(Resources.NubiHR.Approve, "LeaderApprove", new { id = item.Id }) |
                    @Html.ActionLink(Resources.NubiHR.Reject, "Reject", new { id = item.Id }) |
                    @Html.ActionLink(Resources.NubiHR.Details, "Details", "PermissionRequest", new { id = item.Id }, null)
                </td>
               
            </tr>
        }
    </tbody>
</table>

HRSystem/Views/PermissionRequest/ManagerRequests.cshtml
@model IEnumerable<HRSystem.Models.PermissionRequest>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = Resources.NubiHR.ManagerRequests;
    HRSystem.Manager.Helper helperx = new HRSystem.Manager.Helper();
    HRSystem.Manager.RequestManager mngr = new HRSystem.Manager.RequestManager();
    var IsArabic = Request.Cookies["culture"].Value == "ar" ? true : false;
}

<h2>@Resources.NubiHR.PermissionRequests</h2>



<table id="assets-data-table" class="table table-striped table-bordered table-responsive">
    <thead>
        <tr>
            <th>
                @Resources.NubiHR.EmployeeName
            </th>
            
            <th>
                @Resources.NubiHR.Position
            </th>
            
            <th>
                @Resources.NubiHR.RequestDate
            </th>
            
            <th>
                @Resources.NubiHR.PermissionDate
            </th>
            
            <th>
                @Resources.NubiHR.PermissionType
            </th>

            <th>
                @Resources.NubiHR.TimeFrom
            </th>

            <th>
                @Resources.NubiHR.TimeTo
            </th>
            
            <th>
                @Resources.NubiHR.Notes
            </th>

            <th>
                @Resources.NubiHR.Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Where(e => e.ManagerApprovement == null && e.LeaderApprovement == true).ToList())
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.FirstName) @Html.DisplayFor(modelItem => item.Employee.LastName)
                </td>
                @if (IsArabic)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Position.PositionNameAr)
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Position.PositionNameEn)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.RequestDate)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.PermissionDate)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.PermissionType.Type)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.TimeFromHours) : @Html.DisplayFor(modelItem => item.TimeFromMinutes)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.TimeToHours) : @Html.DisplayFor(modelItem => item.TimeToMinutes)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                
                <td>
                    @Html.ActionLink(Resources.NubiHR.Approve, "ManagerApprove", new { id = item.Id }) |
                    @Html.ActionLink(Resources.NubiHR.Reject, "Reject", new { id = item.Id }) |
                    @Html.ActionLink(Resources.NubiHR.Details, "Details", "PermissionRequest", new { id = item.Id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>