HRSystem/Models/VacationRequest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    using Resources;
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;

    public partial class VacationRequest
    {
        public long Id { get; set; }
        [Required(ErrorMessageResourceType = typeof(NubiHR), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(NubiHR), Name = "StartDate")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime StartDate { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime EndDate { get; set; }
        public string Address { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime RequestDate { get; set; }
        public string Note { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ResumeDate { get; set; }
        public bool IsDeleted { get; set; }
        public string EmployeeNo { get; set; }
        public int Duration { get; set; }
        public Nullable<bool> LeaderApprovement { get; set; }
        public Nullable<bool> ManagerApprovement { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public int VacationTypeNo { get; set; }
        public string MedicalReport { get; set; }
        public Nullable<bool> LeaderHasSeen { get; set; }
        public Nullable<bool> ManagerHasSeen { get; set; }
        public string AlternativeEmp { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual VacationType VacationType { get; set; }
        public virtual VacationRequest VacationRequest1 { get; set; }
        public virtual VacationRequest VacationRequest2 { get; set; }
    }
}

HRSystem/Controllers/VacationRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRSystem.Models;
using Microsoft.AspNet.Identity;
using System.Globalization;

namespace HRSystem.Controllers
{
    [Authorize]
    public class VacationRequestController : BaseController
    {
        NubiDBEntities db = new NubiDBEntities();
        // GET: VacationRequest
        public ActionResult Index()
        {
           // var current = System.Globalization.CultureInfo.CurrentCulture;
           // current.DateTimeFormat.Calendar = new GregorianCalendar();
            return View(db.VacationRequests.ToList());
        }
        public ActionResult LeaderRequests()
        {
            //List<VacationRequest> vacation
            var vacation = db.VacationRequests.Where(x => x.LeaderApprovement == null).ToList();
            foreach (VacationRequest vac in vacation)

            {

                VacationRequest Existing_vac = db.VacationRequests.Find(vac.Id);

                Existing_vac.LeaderHasSeen = true;

            }
            db.SaveChanges();
           // var current = System.Globalization.CultureInfo.CurrentCulture;
           // current.DateTimeFormat.Calendar = new GregorianCalendar();
            return View(db.VacationRequests.OrderBy(e => e.RequestDate));
        }
        public ActionResult LeaderApprove(int id)
        {
            VacationRequest vac = db.VacationRequests.Find(id);
            if (ModelState.IsValid)
            {
                vac.LeaderApprovement = true;
                db.Entry(vac).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("LeaderRequests");
            }
            return View(db.VacationRequests.ToList());
        }
        public ActionResult Reject(int id)
        {
            VacationRequest vac = db.VacationRequests.Find(id);
            if (ModelState.IsValid)
            {
                vac.IsRejected = true;
                db.Entry(vac).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("LeaderRequests");
            }
            return View(db.VacationRequests.ToList());
        }
        public ActionResult ManagerRequests()
        {
            var vacation = db.VacationRequests.Where(x => x.LeaderApprovement == true).ToList();
            foreach (VacationRequest vac in vacation)

            {

                VacationRequest Existing_vac = db.VacationRequests.Find(vac.Id);

                Existing_vac.ManagerHasSeen = true;

            }
            db.SaveChanges();
           // var current = System.Globalization.CultureInfo.CurrentCulture;
           // current.DateTimeFormat.Calendar = new GregorianCalendar();
            return View(db.VacationRequests.OrderBy(e => e.RequestDate));
        }
        public ActionResult ManagerApprove(int id)
        {
            VacationRequest vac = db.VacationRequests.Find(id);
            if (ModelState.IsValid)
            {
                vac.ManagerApprovement = true;
                db.Entry(vac).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManagerRequests");
            }
            return View(db.VacationRequests.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            Manager.RequestManager mng = new Manager.RequestManager();
            var chk = mng.CheckFivedaysVaction(id: User.Identity.GetUserId());
            if (chk == false)
            {
                TempData["check"] = Resources.NubiHR.YouDidNotCompleteMonthYet;
                return RedirectToAction("Index");
            }
            var vac = mng.AvailableVacation(id: User.Identity.GetUserId());
            if (vac== false)
            {
                TempData["vac"] = Resources.NubiHR.YouDidNotComplete14DaysFromTheLastVacationYouTook;
                return RedirectToAction("Index");
            }
            //ViewBag.EmpNo = new SelectList(db.Employees.ToList(), "Id", "FirstName");
            ViewBag.VacationTypeNo = new SelectList(db.VacationTypes.ToList(), "ID", "Type");
            ViewBag.AlternativeEmp = db.Employees.Where(x => x.IsDeleted == false).OrderBy(x => x.FirstName + x.LastName).Select(x => x.FirstName + " " + x.LastName ).ToList();
            
            //ViewBag.emp = db.AspNetUsers.ToList();
            return View();
        }

        //
        // POST: /VacationRequest/Create
        [HttpPost]
        public ActionResult Create(VacationRequest vac , string StartDateAr, string AlternativeEmp = "")
        {

            ModelState.Remove("StartDate");
            Manager.RequestManager mng = new Manager.RequestManager();
            var NoOfYear = mng.NoOfEmployeeYears(id: User.Identity.GetUserId());
            var total = mng.totalVacationDuration(id: User.Identity.GetUserId());
            var EmpDays = mng.NoOfEmployeeDays(id: User.Identity.GetUserId());
            var HaveTheEmpFatherDeathVacation = mng.EmployeeHaveFatherDeathVacation(id: User.Identity.GetUserId());
            var HaveTheEmpMotherDeathVacation = mng.EmployeeHaveMotherDeathVacation(id: User.Identity.GetUserId());
            var AvailableAccidentalLeave = mng.AvailableAccidentalLeave(id: User.Identity.GetUserId());
            var NoOfAccidentalLeaves = mng.NoOfAccidentalLeave(id: User.Identity.GetUserId());
            string CurrentUser = User.Identity.GetUserId();
            vac.EmployeeNo = db.AspNetUsers.Where(a => a.Id == CurrentUser).FirstOrDefault().EmpNo;
            var IsArabic = Request.Cookies["culture"].Value == "ar-SA" ? true : false;
            if(IsArabic)
            {


                CultureInfo MyCultureInfo = new CultureInfo("en-GB");
                DateTime.Parse(StartDateAr, MyCultureInfo);
                vac.StartDate = DateTime.Parse(StartDateAr, MyCultureInfo);

                //DateTime.Now.ToString("dd dddd , MMMM, yyyy", new CultureInfo("ar-AE"));
                /*vac.StartDate =new DateTime(2018,12,12);*//* DateTime.Parse(StartDateAr, MyCultureInfo);*/
                //vac.StartDate = Convert.ToDateTime(StartDateAr,);
                //vac.StartDate.ToString("dd dddd , MMMM, yyyy", new CultureInfo("en-US"));

                //CultureInfo MyCultureInfo = new CultureInfo("en-US");
                //MyCultureInfo.DateTimeFormat.Calendar = new HijriCalendar();
                //vac.StartDate = DateTime.Parse(StartDateAr, MyCultureInfo);

                //CultureInfo arSA = new CultureInfo("ar-SA");
                //arSA.DateTimeFormat.Calendar = new HijriCalendar();
                //vac.StartDate = DateTime.ParseExact(StartDateAr, "dd/MM/yyyy", arSA);

            }

            //CultureInfo arSA = new CultureInfo("ar-SA");
            //arSA.DateTimeFormat.Calendar = new HijriCalendar();
            //var dateValue = DateTime.ParseExact("29/08/1434", "dd/MM/yyyy", arSA);

            if ((vac.StartDate < DateTime.Today && vac.VacationTypeNo == 1) ||(vac.StartDate < DateTime.Today && vac.VacationTypeNo == 3) || (vac.StartDate < DateTime.Today && vac.VacationTypeNo == 5) || (vac.StartDate < DateTime.Today && vac.VacationTypeNo == 6))
            {
                ModelState.AddModelError("StartDate", "Start date not valid");
            }
            //else if ((vac.EndDate < DateTime.Today && vac.VacationTypeNo == 1) || (vac.StartDate < DateTime.Today && vac.VacationTypeNo == 3) || (vac.StartDate < DateTime.Today && vac.VacationTypeNo == 5) || (vac.StartDate < DateTime.Today && vac.VacationTypeNo == 6))
            //{
            //    ModelState.AddModelError("EndDate", "End Date not valid");
            //}
            else if (vac.VacationTypeNo == 3 && vac.Duration > 1)
            {
                ModelState.AddModelError("Duration", Resources.NubiHR.JustOneDayAllowedForAccidentalLeave);
            }
            else
            { 
            if (ModelState.IsValid)
            {
                if (vac.VacationTypeNo == 1 && vac.Duration > 5 && (total >= NoOfYear))
                {
                    TempData["checkk"] = Resources.NubiHR.YouCantTakeMoreThan5DaysUntilCompleteOneYear;

             
                    ViewBag.VacationTypeNo = new SelectList(db.VacationTypes.ToList(), "ID", "Type", vac.VacationTypeNo);
                        ViewBag.AlternativeEmp = db.Employees.Where(x => x.IsDeleted == false).OrderBy(x => x.FirstName + x.LastName).Select(x => x.FirstName + " " + x.LastName).ToList();

                        //db.Employees.ToList();


                    }
                    else if (vac.VacationTypeNo == 1 && (total >= NoOfYear) || vac.VacationTypeNo == 1 && EmpDays < 92)
                {
                        TempData["normal"] = Resources.NubiHR.YouCantTakeNormalLeave;


                        ViewBag.VacationTypeNo = new SelectList(db.VacationTypes.ToList(), "ID", "Type", vac.VacationTypeNo);
                        ViewBag.AlternativeEmp = db.Employees.Where(x => x.IsDeleted == false).OrderBy(x => x.FirstName + x.LastName).Select(x => x.FirstName + " " + x.LastName).ToList();

                        //ViewBag.emp = db.AspNetUsers.ToList();
                    }
                    else if (vac.VacationTypeNo == 5 && HaveTheEmpFatherDeathVacation == true)
                {
                    TempData["CheckFatherDeathVacation"] = Resources.NubiHR.YouCantTakeThisVacationYouAlreadyTakeFatherDeathVacation;
                    ViewBag.VacationTypeNo = new SelectList(db.VacationTypes.ToList(), "ID", "Type", vac.VacationTypeNo);
                        ViewBag.AlternativeEmp = db.Employees.Where(x => x.IsDeleted == false).OrderBy(x => x.FirstName + x.LastName).Select(x => x.FirstName + " " + x.LastName).ToList();

                        //ViewBag.emp = db.AspNetUsers.ToList();
                    }

HRSystem/Views/VacationRequest/Create.cshtml
@model HRSystem.Models.VacationRequest
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Create";
    HRSystem.Manager.Helper helperx = new HRSystem.Manager.Helper();
    HRSystem.Manager.RequestManager mngr = new HRSystem.Manager.RequestManager();
}

<h2>@Resources.NubiHR.VacationRequests</h2>
@using (Html.BeginForm(null, null, FormMethod.Post))
{
   
    <div class="form-group col-md-6">
        <div>
            @Resources.NubiHR.EmployeeName
        </div>
        <div>
            <label> @helperx.GetName(User.Identity.GetUserId()).Employee.FirstName @helperx.GetName(User.Identity.GetUserId()).Employee.LastName</label>
        </div>
        <br />
        <div>
            @Resources.NubiHR.Position
        </div>
        <div>
            <label> @helperx.GetUserRole(User.Identity.GetUserId())</label>
        </div>
        <br />
        
        <label>
            @Resources.NubiHR.VacationType
        </label>
        <div>
            @Html.Hidden("VacationTypeNo")
            
                        @Html.DropDownList("VacationTypeNoMain", new List<SelectListItem>
        {
           new SelectListItem{ Text= Resources.NubiHR.Select, Value = "" },
           new SelectListItem{ Text=Resources.NubiHR.NormalLeave, Value = "1" },
           new SelectListItem{ Text=Resources.NubiHR.SickLeave, Value = "2" },
           new SelectListItem{ Text=Resources.NubiHR.AccidentalLeave, Value = "3" },
           new SelectListItem{ Text=Resources.NubiHR.Other, Value = "4" },
        }, new { @class = "form-control" })
            @*@Html.DropDownList("VacationTypeNo", null, "Select", new { @class = "form-control" })*@
        </div>
        <br />
        <div id="Other">
            @*@Html.DropDownList("VacationTypeNo", null, "Select", new { @class = "form-control" })*@

            @Html.DropDownList("VacationTypeNoOther", new List<SelectListItem>{
   new SelectListItem{ Text= Resources.NubiHR.FatherDeath, Value = "5" },
   new SelectListItem{ Text= Resources.NubiHR.MotherDeath, Value = "6" },
} , new { @class = "form-control" })

        </div>
        
        <br />
        <div id="MedicalReport">
            <div>
                @Resources.NubiHR.MedicalReport
            </div>
            <div>
                @Html.TextBoxFor(model => model.MedicalReport, new { type = "file", id = "file4", onchange = "return fileValidation('file4')", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MedicalReport, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div>
            @Resources.NubiHR.PleaseAcceptMyVacationDescribedAboveForAPeriodOf
        </div>
        <div>
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" , required = "required" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
        <br />
        <div>
            @Resources.NubiHR.From
        </div>
        <div class="input-group mb-4">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            <div class="input-group-append">
                <span class="fa fa-calendar input-group-text start_date_calendar" aria-hidden="true"></span>
            </div>
            @Html.Hidden("StartDateAr")
            
        </div>
        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        <br />
        <br />
        <div>
            @Resources.NubiHR.To
        </div>
        <br />
        <div>
            @*@Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control",disabled="disabled" } })*@
            @*<div class="input-group-append">
                <span class="fa fa-calendar input-group-text end_date_calendar" aria-hidden="true"></span>
            </div>*@

            <label id="ED" style="color: #de340d"></label>

            
            @*@Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })*@
        </div>
        <br />
        <div>
            @Resources.NubiHR.ResumeDate
        </div>
        <br />
        <div>
            @*@Html.EditorFor(model => model.ResumeDate, new { htmlAttributes = new { @class = "form-control" } })
            <div class="input-group-append">
                <span class="fa fa-calendar input-group-text resume_date_calendar" aria-hidden="true"></span>
            </div>*@
            @*<br />
            @Html.ValidationMessageFor(model => model.ResumeDate, "", new { @class = "text-danger" })*@
            <label id="RD" style="color: #de340d"></label>
        </div>
        <br />
        <div>
            @Resources.NubiHR.MyAddressDuringVacation
        </div>
        <div>
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
        <br />
        <div>
        @Resources.NubiHR.TheAlternativeEmployeeWillBe
    </div>
    <div>
        @*@Html.DropDownList("AlternativeEmp", null, Resources.NubiHR.Select, new { @class = "form-control" })*@

        @Html.DropDownList("AlternativeEmp", new SelectList(@ViewBag.AlternativeEmp, string.Empty, string.Empty), Resources.NubiHR.Select, new { @class = "form-control"})

        @*@Html.DropDownList("AlternativeEmp", new SelectList(@ViewBag.AlternativeEmp, "Id"), Resources.NubiHR.Select, new { @class = "form-control",})*@

    </div>
            <br/>
        <div>
            @Resources.NubiHR.Notes
        </div>
        <div>
            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <br />
        <div class="form-group">
            <div>
                <input type="submit" value=@Resources.NubiHR.Send class="btn2" />
                
            </div>
            <br />
            <div>
                <a href="@Url.Action("Index")" class="btn-Back" style="color:white; text-decoration: none;">@Resources.NubiHR.Back</a>
            </div>

        </div>
    </div>
}

<script type="text/javascript">

    $(document).ready(function ()
    {
        $("#MedicalReport").hide();
    }
    )

    $(document).ready(function () {
        $("#Other").hide();
    }
    )


    $(function () {
        $("#VacationTypeNoOther").change(function () {
        
              
             
                var OtherID = $("#VacationTypeNoOther").val();
                $("#VacationTypeNo").val(OtherID);
            
           
        });
    });

    $(function () {
        $("#VacationTypeNoMain").change(function () {

            $("#VacationTypeNo").val($("#VacationTypeNoMain").val());
            
          
            if ($("#VacationTypeNo").val() == "2") {
                $("#MedicalReport").show();
            }
            else {
                $("#MedicalReport").hide();
            }

            if ($("#VacationTypeNo").val() == "4") {
          
                $("#Other").show();
                var OtherID = $("#VacationTypeNoOther").val();
                $("#VacationTypeNo").val(OtherID);
   
            }
            else {
                $("#Other").hide();
            }
        });
    });
    
            function fileValidation(element) {
                var fileInput = document.getElementById(element);
                var filePath = fileInput.value;
                var allowedExtensions = /(\.jpg|\.jpeg|\.png|\.gif|\.pdf)$/i;
                if (!allowedExtensions.exec(filePath)) {
                    swal(`@Resources.NubiHR.Error`, '@Resources.NubiHR.UploadAllowedMedicalExtensions', `error`);
                    fileInput.value = '';
                    return false;
                } else {
                    //Image preview
                    if (fileInput.files && fileInput.files[0]) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            document.getElementById('imagePreview').innerHTML = '<img src="' + e.target.result + '"/>';
                        };
                        reader.readAsDataURL(fileInput.files[0]);
                    }
                }
            }

    
            $("#StartDate").change(function () {
                try {
                    var duration = /*parseInt*/($("#Duration").val());
                    var startday = new Date($("#StartDate").val());
                    //var ed = new Date();
                    //var rd = new Date();
                    //ed.setDate(startday.getDate() + duration);
                    //rd.setDate(startday.getDate() + duration + 1);
                    //$("#ED").text(ed.toDateString());
                    //$("#RD").text(rd.toDateString());
                    var end_date = moment(startday).add(duration, 'day');
                    var last_ed = moment(end_date).subtract(1, 'day');




                    //if (last_ed.format('dddd') == "Friday")
                    //{
                    //      last_ed= moment(last_ed).add(1, 'day');
                    //}


                    //else if (last_ed.format('dddd') == "Saturday")
                    //{
                    //    last_ed=  moment(last_ed).add(1, 'day');
                    //}

                    var resume_date = moment(last_ed).add(1, 'days');
                    if (resume_date.format('dddd') == "Friday") {
                        resume_date = moment(resume_date).add(2, 'day');
                    }
                    else if (resume_date.format('dddd') == "Saturday") {
                        resume_date = moment(resume_date).add(1, 'day');
                    }
                    //else if (resume_date.format('dddd D MMM YYYY') == "Saturday") {
                    //    moment(resume_date).add(1, 'day');
                    //}

                    $("#ED").text(last_ed.format('dddd D MMM YYYY'));
                    $("#RD").text(resume_date.format('dddd D MMM YYYY'));
                }
                catch (err) {
                    alert(err);
                   

                }
                
            })


            $("#StartDate").change(function () {
                $("#StartDateAr").val($("#StartDate").val());
            })

</script>

HRSystem/Views/VacationRequest/Delete.cshtml
@model HRSystem.Models.VacationRequest
@{
    ViewBag.Title = "Delete";
}

<h2>@Resources.NubiHR.Delete</h2>
@using (Html.BeginForm(null, null, FormMethod.Post))
{
    <h3>@Resources.NubiHR.AreYouSureYouWantToDeleteThis</h3>

    <div>

        @Html.ActionLink(Resources.NubiHR.Back, "Index", new { @class = "btn btn-primary" }) |
        <input type="submit" value=@Resources.NubiHR.Delete class="btn btn-danger" />
    </div>
}

HRSystem/Views/VacationRequest/LeaderRequests.cshtml
@model IEnumerable<HRSystem.Models.VacationRequest>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "LeaderRequests";
    HRSystem.Manager.Helper helperx = new HRSystem.Manager.Helper();
    var IsArabic = Request.Cookies["culture"].Value == "ar" ? true : false;
}

<h2>@Resources.NubiHR.VacationRequests</h2>

<table id="assets-data-table" class="table table-striped table-bordered table-responsive">
    <thead>
        <tr>
            <th>
                @Resources.NubiHR.EmployeeName
            </th>
            
            <th>
                @Resources.NubiHR.Position
            </th>
           
            <th>
                @Resources.NubiHR.RequestDate
            </th>
           
            <th>
                @Resources.NubiHR.VacationType
            </th>

            <th>
                @Resources.NubiHR.StartDate
            </th>

            <th>
                @Resources.NubiHR.EndDate
            </th>

            <th>
                @Resources.NubiHR.Duration
            </th>

            <th>
                @Resources.NubiHR.ResumeDate
            </th>

            <th>
                @Resources.NubiHR.Address
            </th>

            <th>
                @Resources.NubiHR.AlternativeEmp
            </th>
            
            <th>
                @Resources.NubiHR.Notes
            </th>

            <th>
                @Resources.NubiHR.Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Where(e => e.LeaderApprovement == null).ToList())
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.FirstName)
                </td>
                @if (IsArabic)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Position.PositionNameAr)
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Position.PositionNameEn)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.RequestDate)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.VacationType.Type)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.ResumeDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.AlternativeEmp)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>

                <td>
                    @Html.ActionLink(Resources.NubiHR.Approve, "LeaderApprove", new { id = item.Id }) |
                    @if (item.VacationType.Type != "Sick leave")
                    {
                        @Html.ActionLink(Resources.NubiHR.Reject, "Reject", new { id = item.Id }) <text>|</text>
                    }
                    else
                    {
                        <a href="#" style="color:gray;cursor:not-allowed">@Resources.NubiHR.Reject</a> <text>|</text>

                    }
                    
                    @Html.ActionLink(Resources.NubiHR.Details, "Details", "VacationRequest", new { id = item.Id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>

HRSystem/Views/VacationRequest/ManagerRequests.cshtml
@model IEnumerable<HRSystem.Models.VacationRequest>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "ManagerRequests";
    HRSystem.Manager.Helper helperx = new HRSystem.Manager.Helper();
    var IsArabic = Request.Cookies["culture"].Value == "ar" ? true : false;
}

<h2>@Resources.NubiHR.VacationRequests</h2>

<table id="assets-data-table" class="table table-striped table-bordered table-responsive">
    <thead>
        <tr>
            <th>
                @Resources.NubiHR.EmployeeName
            </th>
            
            <th>
                @Resources.NubiHR.Position
            </th>
           
            <th>
                @Resources.NubiHR.RequestDate
            </th>
            
            <th>
                @Resources.NubiHR.VacationType
            </th>

            <th>
                @Resources.NubiHR.StartDate
            </th>

            <th>
                @Resources.NubiHR.EndDate
            </th>

            <th>
                @Resources.NubiHR.Duration
            </th>

            <th>
                @Resources.NubiHR.ResumeDate
            </th>

            <th>
                @Resources.NubiHR.Address
            </th>

            <th>
                @Resources.NubiHR.AlternativeEmp
            </th>
            
            <th>
                @Resources.NubiHR.Notes
            </th>

            <th>
                @Resources.NubiHR.Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Where(e => e.ManagerApprovement == null && e.LeaderApprovement == true).ToList())
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.FirstName)
                </td>
                @if (IsArabic)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Position.PositionNameAr)
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Position.PositionNameEn)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.RequestDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VacationType.Type)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.ResumeDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.AlternativeEmp)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
               

                <td>
                    @Html.ActionLink(Resources.NubiHR.Approve, "ManagerApprove", new { id = item.Id }) |
                    @Html.ActionLink(Resources.NubiHR.Reject, "Reject", new { id = item.Id }) |
                    @Html.ActionLink(Resources.NubiHR.Details, "Details", "VacationRequest", new { id = item.Id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>